---
title: "Blogposts"
---

Here is a list with short essays published online presenting historical data. The examples here are quite varied in terms of length, style and so on. They are only meant as samples for ideas and inspiration. Do not feel obliged to follow them. Feel free to find your own style. Although not written by a historian, pay also special attention to these posts on [understanding gender in art history data](https://juliasilge.com/blog/art-history/) and [gender roles in Jane Austen's novels](https://juliasilge.com/blog/gender-pronouns/) for examples of how to integrate code and writing.

- [Convict tattoos](https://www.digitalpanopticon.org/Convict_tattoos) (see also [Tattoos, 1793-1925](https://www.digitalpanopticon.org/Tattoos,_1793-1925))

- [Postal geography and the Golden West](https://cblevins.github.io/posts/postal-geography-and-the-golden-west/) (see also [A Dissertation's infancy: The geography of the post](https://cblevins.github.io/posts/a-dissertations-infancy-the-geography-of-the-post/))

- [Text analysis of Martha Ballard's diary](https://cblevins.github.io/posts/text-analysis-of-martha-ballards-diary-part-1/) (and [Part 2](https://cblevins.github.io/posts/text-analysis-of-martha-ballards-diary-part-2/) and [Part 3](https://cblevins.github.io/posts/text-analysis-of-martha-ballards-diary-part-3/))

- [The language of the State of the Union](https://www.theatlantic.com/politics/archive/2015/01/the-language-of-the-state-of-the-union/384575/) (see also [Mapping the State of the Union](https://www.theatlantic.com/politics/archive/2015/01/mapping-the-state-of-the-union/384576/))

- [What years do historians write about?](https://sappingattention.blogspot.com/2013/05/what-years-do-historians-write-about.html) and [Turning-points years in history](https://sappingattention.blogspot.com/2013/05/turning-point-years-in-history.html)

- [Seeing things differently: Visualising patterns of data from the Old Bailey Procceedings](https://blog.digitalpanopticon.org/seeing-things-differently-visualising-patterns-of-data-from-the-old-bailey-proceedings/)

- [A better map of slavery in 1860](https://lincolnmullen.com/blog/a-better-map-of-slavery-in-1860/)

- [Historical religion data in the NHGIS and what you can do with it](https://lincolnmullen.com/blog/historical-religion-data-in-the-nhgis-and-what-you-can-do-with-it/)

- [Missing girls in Italy, 1861-1921](https://cepr.org/voxeu/columns/missing-girls-liberal-italy-1861-1921) (see also [Sex ratios and missing girls in 19^th^-century Europe](https://ehs.org.uk/sex-ratios-and-missing-girls-in-nineteenth-century-europe/))

- [When Mercy Became Planning: Italy’s Foundling Wheels and the Hidden Economics of Abandonment](https://ehs.org.uk/when-mercy-became-planning-italys-foundling-wheels-and-the-hidden-economics-of-abandonment/)

- [Quantifying the ATS: Using Library Catalog Data for historical research](https://lincolnmullen.com/blog/quantifying-the-ats-using-library-catalog-data-for-historical-research/)

- [What age did people marry in the British past?](https://www.campop.geog.cam.ac.uk/blog/2024/07/11/what-age-did-people-marry/)

- [When did England and Wales industrialise?](https://www.campop.geog.cam.ac.uk/blog/2025/01/02/when-did-england-industrialise/)

- [The making of America: Migration in colonial times](https://www.broadstreet.blog/p/the-making-of-america-migration-in)

- [The spread of Romantic nationalism across Europe: A case of ideational difussion](https://www.broadstreet.blog/p/the-spread-of-romantic-nationalism)

- [Stalin's famine](https://www.broadstreet.blog/p/stalins-famine)

- [The instability of gender](https://tedunderwood.com/2016/01/09/the-instability-of-gender/)

- [What did women and men do in Early Modern England?](https://earlymodernwomenswork.wordpress.com/2018/03/09/the-projects-findings-what-work-did-women-and-men-do-in-early-modern-england/)

- [The Correspondence Network of Daniel van der Meulen, 1578–1591](https://www.jessesadler.com/project/dvdm-correspondence)

- [A new lens into the Archive](https://generativelives.substack.com/p/a-new-lens-into-the-archive?r=fbg8f&utm_campaign=post&utm_medium=web&triedRedirect=true)

- [The writing is on the wall for handwriting recognition](https://newsletter.dancohen.org/archive/the-writing-is-on-the-wall-for-handwriting-recognition)
