project:
  type: website
  output-dir: docs
  
website:
  title: "Computational History - HIST2025"
  
  navbar:
    type: inverse
    right:
    - text: "Overview"
      icon: fa-home
      href: index.qmd
    - text: "Syllabus"
      icon: fa-home
      href: syllabus.qmd      
    - text: "Instructions"
      icon: fa-list-ul
      href: instructions.qmd
    - text: "Intro to R"
      icon: fa-book
      href: get-r.qmd      
    - text: "Case-studies"
      icon: fa-book
      menu: 
      - text: "The Paisley Prisoners"
        href: backg-paisley.qmd
      - text: "The State of the Union Speeches"
        href: backg-speeches.qmd
      - text: "The Tudor Network of Letters"
        href: backg-tnp.qmd  
    - text: "Other sources"
      href: other-data.qmd
    - text: "Further readings"
      href: further-readings.qmd  
  sidebar:
    title: "Contents"
    style: "docked"
    # pinned: true
    # collapse-level: 3
    contents:
      - text: "Contents"
        file: index.qmd
      - section: "1. Describing the past"
        contents: 
          - text: "1.1. Qualitative dimensions"
            #file: r-scripts/desc_qual.qmd
          - text: "1.2. Numerical variables" 
            #file: r-scripts/desc_num.qmd
          - text: "1.3. Comparing dimensions" 
            #file: r-scripts/desc_bivar.qmd 
          - text: "1.4. Textual information" 
            #file: r-scripts/desc_text.qmd   
          - text: "1.5. Mapping" 
            #file: r-scripts/mapping.qmd  
          - text: "1.6. Social networks" 
            #file: r-scripts/networks.qmd              
      - text: "2. Dealing with uncertainty"
        #file: r-scripts/uncert.qmd
      - section: "3. Writing history in Quarto"
        contents:   
          - text: "3.1 PDFs"
          - text: "3.2 Blogposts"
bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fig-cap-location: margin
    fig-align: center
    linkcolor: $blue
